### ISSUE TITLE
docker: readlink: missing operand

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#10]
Need to debug why we get this:
```
[cbrake2@happy yoe-distro]$ bitbake core-image-minimal
readlink: missing operand
Try 'readlink --help' for more information.
```

**Comment by kraj** [comment]
it seems its related to here

https://github.com/YoeDistro/yoe-distro/blob/master/envsetup.sh#L400

Can you confirm ?

**Comment by cbrake** [comment]
yes, -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent is the issue for accounts that don't have ssh-agent set up.

One solution: https://github.com/YoeDistro/yoe-distro/pull/11
