### ISSUE TITLE
error recursing submodule meta-96boards at clone stage

### ISSUE THREAD

**Issue by s-maynard** [YoeDistro/yoe-distro#160]
Submodule path 'sources/bitbake': checked out '30fe86d22c239afa75168cc5eb262b880886ef8a'
error: Server does not allow request for unadvertised object e17667875812f4b02ad2749df63a4871f23bbfd9
Fetched in submodule path 'sources/meta-96boards', but it did not contain e17667875812f4b02ad2749df63a4871f23bbfd9. Direct fetching of that commit failed.

**Comment by kraj** [comment]
@s-maynard is this with master branch ?

**Comment by kraj** [comment]
Can you try after updating again https://github.com/YoeDistro/yoe-distro/pull/161 should have fix it

**Comment by s-maynard** [comment]
Thanks!
