### ISSUE TITLE
add meta-variscite SOM BSP layer to project

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#2]
Need to clean up issues where these layers don't play nice with other BSP layers.

**Comment by kraj** [comment]
Right now we have disabled few BSP layers among them are meta-ti meta-intel and fslc
eventually we should be able to add them provided they are made multi-BSP friendly

**Comment by otavio** [comment]
I'd use meta-freescale instead as it has mainline support for this machine and is well maintained.

**Comment by kraj** [comment]
@otavio thanks, can you review

https://github.com/YoeDistro/yoe-distro/pull/3/commits/5afe17de1919d49c602f002669f63ef10a062b06

https://github.com/YoeDistro/yoe-distro/pull/3/commits/9330486f2b087948170bd17ea8486c1b57b26107

**Comment by otavio** [comment]
It seems good.

**Comment by kraj** [comment]
Added few new boards to env

**Comment by kraj** [comment]
The layer is already part of master template since d7897e5c
