### ISSUE TITLE
evaluate swupdate

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#277]
https://github.com/sbabic/swupdate

seems to be the industry standard

**Comment by kraj** [comment]
A nice comparison of update tools
https://drive.google.com/file/d/0B3kuwwmcn4bONFpUQTV1M0NyT1U/view

**Comment by kraj** [comment]
I have been able to try a flip-flop image on rpi3 and it works flawlessly. It also upgraded the image and switched to it after reboot

**Comment by kraj** [comment]
https://github.com/YoeDistro/meta-yoe/pull/51 adds some more bits to support swupdate

**Comment by cbrake** [comment]
@kraj we can probably close this for now -- reopen if you are still doing work on this.
