### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#28]
Would like a documented way to switch between sysvinit and systemd, and test on a number of platforms.

**Comment by cbrake** [comment]
interesting comparing the disk usage of sysvinit to systemd image for core-image-minimal on rPI2, 4.7MB vs 33MB. Adding up the sizes in the buildhistory file, I get 22MB for systemd image, and 4.3MB for sysvinit, so perhaps part of the issue is file system efficiency with small files or something.

History files are attached -- you can open easily by renaming the file to have a *.csv extension, then running soffice <file.csv>

[package-sizes-systemd.txt](https://github.com/YoeDistro/yoe-distro/files/2460784/package-sizes-systemd.txt)
[package-sizes-sysvinit.txt](https://github.com/YoeDistro/yoe-distro/files/2460785/package-sizes-sysvinit.txt)

**Comment by cbrake** [comment]
The sysvinit image has 696 files, and the systemd image has 1,806 files.

**Comment by kraj** [comment]
yes ~16M overhead with systemd I see. compare the size of .tar.bz2 rootfs and not wic image. Because wic image will be aligned so there might be padding.

**Comment by cbrake** [comment]
I was looking at actual space used on running system using df to get 4.7MB and 33MB.

**Comment by kraj** [comment]
you might have to ignore directories like /var/log and /var/tmp since they might contain generated files after boot. Especially the  journal.

**Comment by cbrake** [comment]
/var only has 177KB in it -- hmm.

**Comment by cbrake** [comment]
closing for now -- re-open if you think there is anything else we need to do for this.
