### ISSUE TITLE
drop meta-python2 from layermix

### ISSUE THREAD

**Issue by kraj** [YoeDistro/yoe-distro#305]
python2 is EOL since Jan 2020, and so far we have had issues building other pieces with python3 but it seems at this point we can build pretty much everything in world builds barring few recipes.

**Comment by cbrake** [comment]
sounds good to me

**Comment by kraj** [comment]
hmm it seems meta-browser still needs it
```
ERROR: ParseError at /mnt/b/yoe/sources/meta-browser/dynamic-layers/rust-layer/recipes-browser/mozilla-devscripts/mozilla-devscripts_git.bb:15: Could not inherit file classes/distutils.bbclass

```

I wonder if we should just drop meta-browser too and replace it with meta-webkit

**Comment by cbrake** [comment]
that seems fine to me -- the target applications for Yoe are embedded systems, so as long as we have one good browser solution, I don't think we need meta-browser.
