### ISSUE TITLE
no Intel X86_64 baremetal build environments?

### ISSUE THREAD

**Issue by outbackdingo** [YoeDistro/yoe-distro#375]
looks like a nice project however i dont see an intel bare metal x86_64 or i7 examples like i would see in meta-intel

**Comment by kraj** [comment]
@outbackdingo we do have minnowboard-max sample [1] but it should be possible to add
any board you have in meta-intel here by just symlinking `envsetup.sh` to `MACHINE-envsetup.sh`

something like

`ln -s envsetup.sh intel-corei7-64-envsetup.sh`


https://github.com/YoeDistro/yoe-distro/blob/dunfell/minnowboard-max-envsetup.sh

**Comment by kraj** [comment]
I have proposed a fix here https://github.com/YoeDistro/yoe-distro/pull/374

**Comment by kraj** [comment]
This should be now fixed as pull request is merged
