### ISSUE TITLE
working with podman

### ISSUE THREAD

**Issue by outbackdingo** [YoeDistro/yoe-distro#429]
Hi, development machine is now Fedora Silverblue 32, it utilizes podman ... docker like but not docker, any posibilities to support podman along with docker?

**Comment by cbrake** [comment]
interesting idea.

You could try substituting podman for docker in this function:

https://github.com/YoeDistro/yoe-distro/blob/dunfell/envsetup.sh#L466

Maybe podman would handle the issue where UID is not 1000 better than docker (https://github.com/YoeDistro/yoe-distro/issues/7)

**Comment by philn** [comment]
Additionally the volumes need to be mounted with the `:z` or `:Z` option, otherwise the envsetup.sh eval within the sandbox will fail. But I still get errors about some folders being read-only... need to debug this further

**Comment by cbrake** [comment]
@philn thanks for your input on this -- I've not had time to try this, but podman looks very interesting for this application.
