### ISSUE TITLE
support DL_DIR outside yoe-distro build dir

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#61]
If users redefine DL_DIR outside the build directory, is there any way to map this directory in docker.
One possibility is to parse the auto/site/local.conf files in envsetup.sh and look for DL_DIR. Ben has used something like this:

```
if [ -f conf/site.conf ]; then
DL_DIR=$(cat conf/site.conf | grep DL_DIR | awk '{print$3}' | tr -d '"')
fi
```
But there may be other ways.

**Comment by openity-ben** [comment]
Just to further clarify, once I parsed DL_DIR from the conf file, I then added the following as a mount point to the docker run command:

-v $DL_DIR:$DL_DIR \

My thought behind this approach was to have a common/shared downloads folder to use across multiple projects and repos without having to re-download packages for each build and consume unnecessary disk space

**Comment by kraj** [comment]
I think this approach looks ok.

**Comment by cbrake** [comment]
@openity-ben can you review/test this and see if it works for you:
https://github.com/YoeDistro/yoe-distro/pull/79
