### ISSUE TITLE
change SIOT OS_VERSION_FIELD env var

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoe-distro#675]
For Yoe, it would be nice to set SIOT_OS_VERSION_FIELD to VERSION_ID, so it will pick up the Yoe version instead of the Yocto version.

https://github.com/simpleiot/simpleiot/blob/master/contrib/siot.service

**Comment by kraj** [comment]
`os-release` is a standard artifact now a days, so perhaps we can read it and extract relevant information programmatically inside simpleIOT app itself perhaps

**Comment by cbrake** [comment]
that is a good idea, so are you are suggesting we extract all the fields? -- is something like the below what you had in mind?

https://github.com/simpleiot/simpleiot/issues/358

**Comment by cbrake** [comment]
information on `/etc/os-release`: 

https://www.freedesktop.org/software/systemd/man/os-release.html
